name: Deploy to Firebase Hosting

on:
  push:
    branches: [ main ]

env:
  CI: true
  VUE_APP_FIREBASE_PROJECT_ID: ${{ secrets.VUE_APP_FIREBASE_PROJECT_ID }}
  VUE_APP_FIREBASE_API_KEY: ${{ secrets.VUE_APP_FIREBASE_API_KEY }}
  VUE_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.VUE_APP_FIREBASE_AUTH_DOMAIN }}
  VUE_APP_FIREBASE_DATABASE_URL: ${{ secrets.VUE_APP_FIREBASE_DATABASE_URL }}
  VUE_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.VUE_APP_FIREBASE_STORAGE_BUCKET }}
  VUE_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VUE_APP_FIREBASE_MESSAGING_SENDER_ID }}
  VUE_APP_FIREBASE_APP_ID: ${{ secrets.VUE_APP_FIREBASE_APP_ID }}
  VUE_APP_GOOGLE_ANALYTICS_ID: ${{ secrets.VUE_APP_GOOGLE_ANALYTICS_ID }}
  VUE_APP_I18N_LOCALE: en
  VUE_APP_I18N_FALLBACK_LOCALE: en

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x] # only use 10, for firebase-tools compatibility
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g yarn @vue/cli
    - run: yarn
    - run: yarn lint

  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x] # only use 10, for firebase-tools compatibility
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g yarn @vue/cli
    - run: yarn install
    - run: yarn versions
    - run: npm list --all --json
    - run: yarn test:unit --detectOpenHandles --forceExit

  deploy:
    name: Deploy
    needs: unit-tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x] # only use 10, for firebase-tools compatibility
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g yarn @vue/cli
    - run: yarn
    - run: yarn build
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy
