# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run Tests

on:
  pull_request:
    branches: [ main ]

env:
  CI: true
  VUE_APP_FIREBASE_PROJECT_ID: ${{ secrets.VUE_APP_FIREBASE_PROJECT_ID }}
  VUE_APP_FIREBASE_API_KEY: ${{ secrets.VUE_APP_FIREBASE_API_KEY }}
  VUE_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.VUE_APP_FIREBASE_AUTH_DOMAIN }}
  VUE_APP_FIREBASE_DATABASE_URL: ${{ secrets.VUE_APP_FIREBASE_DATABASE_URL }}
  VUE_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.VUE_APP_FIREBASE_STORAGE_BUCKET }}
  VUE_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VUE_APP_FIREBASE_MESSAGING_SENDER_ID }}
  VUE_APP_FIREBASE_APP_ID: ${{ secrets.VUE_APP_FIREBASE_APP_ID }}
  VUE_APP_GOOGLE_ANALYTICS_ID: ${{ secrets.VUE_APP_GOOGLE_ANALYTICS_ID }}
  VUE_APP_I18N_LOCALE: en
  VUE_APP_I18N_FALLBACK_LOCALE: en
  FIREBASE_TOKEN: ${{ secrets.CI_FIREBASE_TOKEN }}

jobs:
  linting:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x] # only use 10, for firebase-tools compatibility

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g pnpm @vue/cli
    - run: pnpm install
    - run: pnpm lint

  unit-tests:
    needs: linting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x] # only use 10, for firebase-tools compatibility
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g pnpm @vue/cli
    - run: pnpm
    - run: CI=true pnpm test:unit

  # end2end-tests:
  #   needs: linting
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node-version: [15.x] # only use 10, for firebase-tools compatibility
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Use Node.js ${{ matrix.node-version }}
  #     uses: actions/setup-node@v1
  #     with:
  #       node-version: ${{ matrix.node-version }}
  #   - run: npm install -g yarn @vue/cli
  #   - run: yarn
  #   - run: CI=true yarn ci:e2e
